version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_database
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - '3307:3306'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  algorithm:
    container_name: algorithm
    build:
      context: ./algorithm
      dockerfile: Dockerfile
    ports:
      - '5001:5000'
    networks:
      - app-network

  server:
    depends_on:
      - db
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: {}
