import type { Metadata } from "next";
import localFont from "next/font/local";
import { AudioPlayerProvider } from "../context/audio-player-context";
import { AudioPlayer } from "./components/AudioPlayer";
import "./globals.css";
import Header from "./components/Header/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // TODO: fetch user data
  const userData = {
    avatarUrl: undefined,
    notificationsCount: 3,
  }

  return (
    <AudioPlayerProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Header
            avatarUrl={userData.avatarUrl}
            notificationsCount={userData.notificationsCount}
          />
          <main>
            {children}
          </main>
          <AudioPlayer />
        </body>
      </html>
    </AudioPlayerProvider>
  );
}
